//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace it_company.ItCompanyServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItCompanyServiceClient.IServiceItCompany")]
    public interface IServiceItCompany {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceItCompany/DoWork", ReplyAction="http://tempuri.org/IServiceItCompany/DoWorkResponse")]
        void DoWork(); // look here if right or not
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceItCompany/DoWork", ReplyAction="http://tempuri.org/IServiceItCompany/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceItCompanyChannel : it_company.ItCompanyServiceClient.IServiceItCompany, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceItCompanyClient : System.ServiceModel.ClientBase<it_company.ItCompanyServiceClient.IServiceItCompany>, it_company.ItCompanyServiceClient.IServiceItCompany {
        
        public ServiceItCompanyClient() {
        }
        
        public ServiceItCompanyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceItCompanyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceItCompanyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceItCompanyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() { // look here if right or not
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
